spring.application.name=security-library


common.security.secret-key=3MP8Xi8ExjXcPHbOO3wWLRHJDGqwK6XV
common.security.jwt-ttl=300000

# Health check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
