spring.application.name=eshop-api-gateway

eshop.login.service.url=${ESHOP_LOGIN_SERVICE_URL:http://localhost:8080}
eshop.pymt.service.url=${ESHOP_PYMT_SERVICE_URL:http://localhost:8081}
server.port=8083

eureka.client.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/demo_dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:devuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:devpassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

common.security.secret-key=3MP8Xi8ExjXcPHbOO3wWLRHJDGqwK6XV
common.security.jwt-ttl=300000

#AI agent configuration
spring.ai.mcp.client.enabled=true
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.mcp.client.sse.connections.my-mcp-server.url=${ESHOP_PYMT_SERVICE_URL:http://localhost:8081}
spring.ai.ollama.base-url=${ESHOP_OLLAMA_URL:http://localhost:11434}

# Sliding window size (number of calls to record)
resilience4j.circuitbreaker.instances.loginService.slidingWindowSize=10

# Failure rate threshold (in percentage)
resilience4j.circuitbreaker.instances.loginService.failureRateThreshold=50

# Optional: Common state settings often paired with the above
resilience4j.circuitbreaker.instances.loginService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.loginService.waitDurationInOpenState=60s

resilience4j.retry.instances.loginService.maxAttempts=3
resilience4j.retry.instances.loginService.waitDuration=500ms
resilience4j.retry.instances.loginService.retry-exceptions[0]=feign.RetryableException
resilience4j.retry.instances.loginService.retry-exceptions[1]=feign.FeignException

resilience4j.bulkhead.instances.loginService.maxConcurrentCalls=5
resilience4j.bulkhead.instances.loginService.maxWaitDuration=0ms
resilience4j.bulkhead.instances.loginService.event-consumer-buffer-size=5

logging.level.io.github.resilience4j.retry=TRACE
logging.level.io.github.resilience4j=TRACE
logging.level.org.springframework.aop: DEBUG

# Set the aspect order to ensure that the circuit breaker is applied before the retry logic
resilience4j.circuitbreaker.circuit-breaker-aspect-order=1
resilience4j.retry.retry-aspect-order=2

resilience4j.ratelimiter.instances.loginController.limit-for-period=10
resilience4j.ratelimiter.instances.loginController.limit-refresh-period=3s
resilience4j.ratelimiter.instances.loginController.timeout-duration=0s
resilience4j.ratelimiter.instances.loginController.register-health-indicator=true
resilience4j.ratelimiter.instances.loginController.event-consumer-buffer-size=100