--these script are for demo purposes only, run once to create sample data in the DB

-- truncate table `users`;
--
-- insert into `users` (`id`, `username`, `password`, `full_name`, `enabled`, `role`) values(1, 'user', '{bcrypt}$2a$10$IeofhAYT3lUfrF0bi1aflOat.IU3xOkZWaAWAuVc9jO2.QxTtH4RO', 'User', 1, 'USER');
--
-- alter table `users` AUTO_INCREMENT = 2;
--
-- SET FOREIGN_KEY_CHECKS = 0;
--
-- TRUNCATE TABLE `orders`;
--
-- INSERT INTO `orders` (`id`, `user_id`, `product_id`, `quantity`, `price`, `status`, `created_at`, `order_id`)
-- VALUES (1, 1, 102, 2, 20.98, 'CREATED', CURRENT_DATE, 1001);
--
-- ALTER TABLE `orders` AUTO_INCREMENT = 3;
--
-- SET FOREIGN_KEY_CHECKS = 1;